# organization name, it's used to get github repo url, also in page title
name: koajs

# badge style, can be "flat", "flat-square" or ""
# see http://shields.io/ for details
badge_style: flat-square

# meta headers in html
title:       koajs
description:
keywords:

# list of projects, this will be sorted by name;
# every package is either string or object
projects:
 - koa
 - koala
 - koa-static:
     repo: koajs/static
 - koa-send:
     repo: koajs/send
 - koa-etag:
     repo: koajs/etag
 - koa-csrf:
     repo: koajs/csrf
 - koa-compose:
     repo: koajs/compose
 - koa-route:
     repo: koajs/route
 - koa-trie-router:
     repo: koajs/trie-router
 - koa-spdy-push:
     repo: koajs/spdy-push
 - koa-file-server:
     repo: koajs/file-server
 - koa-compressor:
     repo: koajs/compressor
 - koa-json:
     repo: koajs/json
 - koa-path-match:
     repo: koajs/path-match
 - koa-logger:
     repo: koajs/logger
 - koa-trace:
     repo: koajs/trace
 - koa-favicon:
     repo: koajs/favicon
 - koa-html-minifier:
     repo: koajs/html-minifier
 - koa-cash:
     repo: koajs/cash
 - koa-json-filter:
     repo: koajs/json-filter
 - koa-mount:
     repo: koajs/mount
 - koa-ratelimit:
     repo: koajs/ratelimit
 - koa-compress:
     repo: koajs/compress
 - koa-error:
     repo: koajs/error
 - koa-sendfile:
     repo: koajs/sendfile
 - koa-json-error:
     repo: koajs/json-error
 - koa-basic-auth:
     repo: koajs/basic-auth
 - koa-is-json:
     repo: koajs/is-json
 - koa-session:
     repo: koajs/session
 - koa-conditional-get:
     repo: koajs/conditional-get
 - koa-qs:
     repo: koajs/qs
 - koa-rewrite:
     repo: koajs/rewrite
 - koa-common:
     repo: koajs/common

# list of maintainers, this won't be sorted
maintainers:
 - name:    TJ Holowaychuk
   github:  visionmedia
   npm:     tjholowaychuk
   twitter: tjholowaychuk
   email:   tj@vision-media.ca
   gittip:  visionmedia

 - name:    Jonathan Ong
   github:  jonathanong
   npm:     jongleberry
   twitter: jongleberry
   gittip:  jonathanong
   email:   me@jongleberry.com

   # if gravatar is attached to an email different from specified above,
   # add md5 of it here:
   avatar:  6e33cc0412b61cc01daac23c8989003c

# this determines what info will be fetched with `make db`;
# you can comment out stuff to reduce number of http requests
db.json:
  projects:
   - node        # node version, it's the lowest version from .travis.yml
   - description # package description from package.json (from npm registry)
   - maintainer  # maintainer npm account (= _npmUser of last published ver)
  maintainers:
   - packages    # amount of packages this npm user has
